### ISSUE TITLE
[Bug]: action failure due to rm_dollar_sign() changing code within quotes

### ISSUE THREAD

**Issue by iantaylor-NOAA** [nmfs-ost/ghactions4r#150]
### Describe the bug

I used the dollar sign notation in an error message in quotes without thinking in https://github.com/r4ss/r4ss/blob/ssl-issue/R/get_ss3_exe.r#L79. The `rm_dollar_sign()` action failed due to the replacement of the $ notation with quotes which did not work correctly with the quotes around the message: https://github.com/r4ss/r4ss/actions/runs/12244574072/job/34156592356#step:12:161.

### To Reproduce

Use dollar sign notation in quoted text and run `ghactions4r::rm_dollar_sign()`.

### Expected behavior

I can manually avoid this by using single quotes but it makes me think that the function problem should skip text in quotes. It could automatically detect double quotes and use single quotes, but that seems overly complex. It could give a warning instead of modifying the quoted code, but that also seems too complex. If the code is in quotes the use of dollar sign notation is unlikely to be an issue.

**Comment by e-perl-NOAA** [comment]
I've started a fix to this issue.

**Comment by k-doering-NOAA** [comment]
Thanks @iantaylor-NOAA and @e-perl-NOAA for discovering this! I'm writing out an alternative example of the problem as it took me a little bit to figure out what is happening.

The initial line began with
```r
 "  3. Run curl::curl_version()$ssl_version and confirm"
```
running `rm_dollar_sign()` changed this to
```r
 "  3. Run curl::curl_version()[["ssl_version"]] and confirm"
```

which `{{styler}}` then had issues with because the use of double quotations made it not valid r code.

instead, rm_dollar_sign() should have changed it to
```r
 "  3. Run curl::curl_version()[['ssl_version']] and confirm"
```

or, less ideally, ignoring statements that are in quotes.

This will be a problem for any statements that are in quotes.

**Comment by iantaylor-NOAA** [comment]
Thanks @k-doering-NOAA, this is a good summary. 

It looks like styler handles single quotes well (see https://www.tidyverse.org/blog/2017/12/styler-1.0.0/#:~:text=It%20also%20handles%20single%20quotes), so if `rm_dollar_sign()` can apply a single quote solution if the dollar sign is within double quotes, that seems like an ideal solution to me. Thanks to @e-perl-NOAA, we've implemented that manually in r4ss already.

If there are single quotes around the expression with the dollar sign, the initial run of styler before `rm_dollar_sign()` should change to double quotes, so I think there's no need to worry about that case.

**Comment by k-doering-NOAA** [comment]
I agree, that does seem like the ideal solution!

The documentation implies this was a known issue for a while, although the documentation suggests the function exits on error, which is unfortunately not true: https://github.com/nmfs-fish-tools/ghactions4r/blob/499d1d5a8178d967bb6bbdfc6b3023048d764512/R/rm_dollar_sign.R#L7-L9

I'm still not sure how to fix this, but I wonder if there are clues in the styler source code. we just need to be able to detect when the expression is already in quotes and incorporate that in a regex expression.
